version: '3.9'
services:
  api:
    build: .
    container_name: backend
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
    ports:
      - 8000:8000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 5
